### ISSUE TITLE
Package files with escaped HTML characters don't load properly

### ISSUE THREAD

**Issue by triplepoint** [stevearc/pypicloud#124]
Given a package file named:
`something.something.ops-2016.9.9.23.2.47%2Bbee0714.tar.gz`

With a package METADATA `version`:
`2016.9.9.23.2.47+bee0714`

And having published the package to pypicloud with `twine`:
`twine upload -r my_repo_definition --skip-existing something.something.ops-2016.9.9.23.2.47%2Bbee0714.tar.gz`

I can see the file in the pypi UI, with the above file name and version.

Attempting to install the package with pip:
```
virtualenv env
source env/bin/activate
pip install -i https://my_pypicloud_server/simple/ -vvvv "something.something.ops==2016.6.15.5.33.2+21c64f5.dirty"
```

yields (replacing a few sensitive strings with placeholders):
```
pip install "something.something.ops==2016.6.15.5.33.2+21c64f5.dirty" -i https://my-pypi-cloud-redacted.com/pypi/ -vvvv
Collecting something.something.ops==2016.6.15.5.33.2+21c64f5.dirty
  1 location(s) to search for versions of something.something.ops:
  * https://my-pypi-cloud-redacted.com/pypi/something-something-ops/
  Getting page https://my-pypi-cloud-redacted.com/pypi/something-something-ops/
  Looking up "https://my-pypi-cloud-redacted.com/pypi/something-something-ops/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): my-pypi-cloud-redacted.com
  "GET /pypi/something-something-ops/ HTTP/1.1" 200 577
  Updating cache with response from "https://my-pypi-cloud-redacted.com/pypi/something-something-ops/"
  Analyzing links from page https://my-pypi-cloud-redacted.com/pypi/something-something-ops/
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.1.22.20.3.13%2B124b629.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.1.22.20.3.13+124b629.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.1.23.3.0.0%2B190054c.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.1.23.3.0.0+190054c.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.1.26.0.34.13%2B9ce8ca7.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.1.26.0.34.13+9ce8ca7.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.2.11.2.57.21%2Bd67bf27.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.2.11.2.57.21+d67bf27.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.2.13.1.22.43%2B8aa36bf.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.2.13.1.22.43+8aa36bf.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.2.13.19.19.42%2Bf9d5cd1.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.2.13.19.19.42+f9d5cd1.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.2.13.21.46.57%2B6941a63.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.2.13.21.46.57+6941a63.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.2.3.19.55.20%2Bc09523f.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.2.3.19.55.20+c09523f.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.3.18.17.48.27%2B37f8278.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.3.18.17.48.27+37f8278.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.3.7.19.15.4%2B79bfd50.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.3.7.19.15.4+79bfd50.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.4.1.16.55.25%2Bfbadb71.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.4.1.16.55.25+fbadb71.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.4.14.6.57.10%2B9e4c449.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.4.14.6.57.10+9e4c449.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.4.22.13.53.20%2Bc9ef41b.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.4.22.13.53.20+c9ef41b.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.4.5.2.12.33%2B4a5fd91.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.4.5.2.12.33+4a5fd91.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.4.8.21.44.52%2Bc93ab09.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.4.8.21.44.52+c93ab09.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.5.12.13.16.29%2B98622b9.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.5.12.13.16.29+98622b9.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.5.19.22.19.48%2Bc969909.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.5.19.22.19.48+c969909.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.6.15.5.33.2+21c64f5.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.27.21.5.46%2B9bd9a78.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.6.27.21.5.46+9bd9a78.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.8.11.23.44.50%2Bbdd2c02.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.8.11.23.44.50+bdd2c02
  Using version 2016.6.15.5.33.2+21c64f5.dirty (newest of versions: 2016.6.15.5.33.2+21c64f5.dirty)
  Looking up "https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz" in the cache
  No cache entry available
  "GET /api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz HTTP/1.1" 404 152
  HTTP error 404 while getting https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/)
  Could not install requirement something.something.ops==2016.6.15.5.33.2+21c64f5.dirty from https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz because of error 404 Client Error: Not Found for url: https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz
Cleaning up...
Could not install requirement something.something.ops==2016.6.15.5.33.2+21c64f5.dirty from https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz because of HTTP error 404 Client Error: Not Found for url: https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz for URL https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/)
Exception information:
Traceback (most recent call last):
  File "/somerootdir/test/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/somerootdir/test/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/somerootdir/test/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/somerootdir/test/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/somerootdir/test/lib/python2.7/site-packages/pip/req/req_set.py", line 631, in _prepare_file
    (req_to_install, exc, req_to_install.link)
InstallationError: Could not install requirement something.something.ops==2016.6.15.5.33.2+21c64f5.dirty from https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz because of HTTP error 404 Client Error: Not Found for url: https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz for URL https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/)
```

Whereas doing:
```
pip install -i https://my_pypicloud_server/simple/ -vvvv "something.something.ops==2016.6.15.5.33.2%2B21c64f5.dirty"
```

yields:
```
pip install "something.something.ops==2016.6.15.5.33.2%2B21c64f5.dirty" -i https://my-pypi-cloud-redacted.com/pypi/ -vvvv
Collecting something.something.ops==2016.6.15.5.33.2%2B21c64f5.dirty
  1 location(s) to search for versions of something.something.ops:
  * https://my-pypi-cloud-redacted.com/pypi/something-something-ops/
  Getting page https://my-pypi-cloud-redacted.com/pypi/something-something-ops/
  Looking up "https://my-pypi-cloud-redacted.com/pypi/something-something-ops/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): my-pypi-cloud-redacted.com
  "GET /pypi/something-something-ops/ HTTP/1.1" 200 608
  Updating cache with response from "https://my-pypi-cloud-redacted.com/pypi/something-something-ops/"
  Analyzing links from page https://my-pypi-cloud-redacted.com/pypi/something-something-ops/
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.1.22.20.3.13%2B124b629.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.1.22.20.3.13+124b629.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.1.23.3.0.0%2B190054c.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.1.23.3.0.0+190054c.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.1.26.0.34.13%2B9ce8ca7.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.1.26.0.34.13+9ce8ca7.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.2.11.2.57.21%2Bd67bf27.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.2.11.2.57.21+d67bf27.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.2.13.1.22.43%2B8aa36bf.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.2.13.1.22.43+8aa36bf.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.2.13.19.19.42%2Bf9d5cd1.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.2.13.19.19.42+f9d5cd1.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.2.13.21.46.57%2B6941a63.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.2.13.21.46.57+6941a63.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.2.22.20.6.11%2Bdf7bcaf.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.2.22.20.6.11+df7bcaf.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.2.3.19.55.20%2Bc09523f.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.2.3.19.55.20+c09523f.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.3.18.17.48.27%2B37f8278.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.3.18.17.48.27+37f8278.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.3.7.19.15.4%2B79bfd50.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.3.7.19.15.4+79bfd50.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.3.8.0.26.54%2B7f003e7.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.3.8.0.26.54+7f003e7.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.4.1.16.55.25%2Bfbadb71.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.4.1.16.55.25+fbadb71.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.4.14.6.57.10%2B9e4c449.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.4.14.6.57.10+9e4c449.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.4.22.13.53.20%2Bc9ef41b.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.4.22.13.53.20+c9ef41b.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.4.5.2.12.33%2B4a5fd91.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.4.5.2.12.33+4a5fd91.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.4.8.21.44.52%2Bc93ab09.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.4.8.21.44.52+c93ab09.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.5.12.13.16.29%2B98622b9.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.5.12.13.16.29+98622b9.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.5.19.22.19.48%2Bc969909.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.5.19.22.19.48+c969909.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.15.5.33.2%2B21c64f5.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.6.15.5.33.2+21c64f5.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.6.27.21.5.46%2B9bd9a78.dirty.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.6.27.21.5.46+9bd9a78.dirty
    Found link https://my-pypi-cloud-redacted.com/api/package/something-something-ops/something.something.ops-2016.8.11.23.44.50%2Bbdd2c02.tar.gz (from https://my-pypi-cloud-redacted.com/pypi/something-something-ops/), version: 2016.8.11.23.44.50+bdd2c02
  Could not find a version that satisfies the requirement something.something.ops==2016.6.15.5.33.2%2B21c64f5.dirty (from versions: 2016.1.22.20.3.13+124b629.dirty, 2016.1.23.3.0.0+190054c.dirty, 2016.1.26.0.34.13+9ce8ca7.dirty, 2016.2.3.19.55.20+c09523f.dirty, 2016.2.11.2.57.21+d67bf27.dirty, 2016.2.13.1.22.43+8aa36bf.dirty, 2016.2.13.19.19.42+f9d5cd1.dirty, 2016.2.13.21.46.57+6941a63.dirty, 2016.2.22.20.6.11+df7bcaf.dirty, 2016.3.7.19.15.4+79bfd50.dirty, 2016.3.8.0.26.54+7f003e7.dirty, 2016.3.18.17.48.27+37f8278.dirty, 2016.4.1.16.55.25+fbadb71.dirty, 2016.4.5.2.12.33+4a5fd91.dirty, 2016.4.8.21.44.52+c93ab09.dirty, 2016.4.14.6.57.10+9e4c449.dirty, 2016.4.22.13.53.20+c9ef41b.dirty, 2016.5.12.13.16.29+98622b9.dirty, 2016.5.19.22.19.48+c969909.dirty, 2016.6.15.5.33.2+21c64f5.dirty, 2016.6.27.21.5.46+9bd9a78.dirty, 2016.8.11.23.44.50+bdd2c02)
Cleaning up...
No matching distribution found for something.something.ops==2016.6.15.5.33.2%2B21c64f5.dirty
Exception information:
Traceback (most recent call last):
  File "/somerootdir/test/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/somerootdir/test/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/somerootdir/test/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/somerootdir/test/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/somerootdir/test/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/somerootdir/test/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/somerootdir/test/lib/python2.7/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for something.something.ops==2016.6.15.5.33.2%2B21c64f5.dirty
```

So there appears to be an http-encoding interpretation issue somewhere between tracking down the file via the `/pypi/` endpoint, and fetching the file over the `/api/` endpoint.

Any ideas?

**Comment by triplepoint** [comment]
I should say, I'm using S3 as the storage backend, and Postgres (SQL) as the cache backend.

**Comment by triplepoint** [comment]
Digging a bit more, I found some additional facts:

For a published package file named:  `something.something.ops-2016.3.27.7.11.26%2B9d3cd9a.dirty.tar.gz`

the pypicloud repo's `simple` listing at `https://my-server-redacted.com/pypi/something-something-ops/` includes a corresponding file:
```
something.something.ops-2016.3.27.7.11.26%2B9d3cd9a.dirty.tar.gz
```
with a url like:
```
https://my-server-redacted.com/api/package/something-something-ops/something.something.ops-2016.3.27.7.11.26%2B9d3cd9a.dirty.tar.gz
```

Which looks legit, however it returns a 404, which is consistent with the pip behavior reported earlier.

Digging directly through the S3 bucket turns up a file with a `key`:
`something.something.ops-2016.3.27.7.11.26%2B9d3cd9a.dirty.tar.gz` which seems to match, but the `link` associated with that item is:
```
https://s3-us-gov-west-1.amazonaws.com/my-bucket-name/000c/something-something-ops/something.something.ops-2016.3.27.7.11.26%252B9d3cd9a.dirty.tar.gz
```

Note the extra `52` in the file name.   Sure enough, hitting the pypi api endpoint at that malformed name successfully downloads the package file:
```
https://my-server-redacted.com/api/package/something-something-ops/something.something.ops-2016.3.27.7.11.26%252B9d3cd9a.dirty.tar.gz
```

testing urlencoding:
```
>>> import urllib
>>> print urllib.urlencode({'foo': '%'})
foo=%25
>>> print urllib.urlencode({'foo': '%2b'})
foo=%252b
```

So something somewhere is doubly-url-encoding the package name.  I can verify that the original encoding is definitely coming from `setuptools` during the package creation process, because the package `setup.py` itself has a version string with a `+` in it, but doing `python setup.py sdist` definitely generates a file with an escaped file name.

Any chance this is a simple boto "please don't escape the file name" thing? :)

**Comment by triplepoint** [comment]
It's worth noting that changing the config:
```
storage.redirect_urls = False
```

Does end up generating the properly (that is, doubly) escaped AWS links.  So boto's key.generate_url() code is at least working appropriately.

I spent some time digging into pypicloud's code to see if I could figure out why the redirect url's are 404'ing in this case, but I came up dry.  Please let me know if there's anything I can do to help diagnose this.

**Comment by triplepoint** [comment]
I tried turning on SQL logging, specifically to see what's happening in `/pypicloud/views/api.py` in `download_package()` around line 72.  I suspect that SQL query is failing to return a match if the file name has `%NN` escaped names.  And sure enough:

```
curl --insecure https://172.28.128.9/api/package/something-something-ops/something.something.ops-2016.3.4.22.20.44%2B6745d84.dirty.tar.gz
<html>
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
  The resource could not be found.<br/><br/>
 </body>
</html>
```

And the query logs:
```
INFO 2017-05-17 21:56:51,055 [sqlalchemy.engine.base.Engine] BEGIN (implicit)
INFO 2017-05-17 21:56:51,056 [sqlalchemy.engine.base.Engine] SELECT packages.filename AS packages_filename, packages.name AS packages_name, packages.version AS packages_version, packages.last_modified AS packages_last_modified, packages.summary AS packages_summary, packages.data AS packages_data
FROM packages
WHERE packages.filename = ?
 LIMIT ? OFFSET ?
INFO 2017-05-17 21:56:51,056 [sqlalchemy.engine.base.Engine] (u'something.something.ops-2016.3.4.22.20.44+6745d84.dirty.tar.gz', 1, 0)
DEBUG 2017-05-17 21:56:51,057 [sqlalchemy.engine.base.Engine] Col ('packages_filename', 'packages_name', 'packages_version', 'packages_last_modified', 'packages_summary', 'packages_data')
INFO 2017-05-17 21:56:51,192 [sqlalchemy.engine.base.Engine] ROLLBACK
```
So that `context.filename` value ends up being escaped when it shouldn't be, and therefore that SQL query returns zero results, which forces PYPICloud to try the fallback repo (pypi), which fails to find anything, which results in a 404.

So now it just comes down to figuring out why/how pyramid's context is being auto escaped, and whether there's a way to avoid that.

**Comment by triplepoint** [comment]
I'm not sure I want to submit a PR for this one, because the fix is pretty ugly, but this at least technically works:
https://github.com/stevearc/pypicloud/compare/master...triplepoint:master

There has to be a better way to get the un-escaped path fragments out of Pyramid, but I don't know the framework well enough to know how to do it.  So in the meantime I'll run this in production.

Any advice would be greatly appreciated.

**Comment by triplepoint** [comment]
See #127 for the resolution here, turns out there was a bug on our end.
