### ISSUE TITLE
SQL cache `version` field too small for some packages

### ISSUE THREAD

**Issue by triplepoint** [stevearc/pypicloud#126]
Wheels have started showing up in pypi with huge version strings.  The varchar 50 assumption in pypicloud doesn't have enough size to cover it.  For example:
https://pypi.python.org/pypi/scipy/0.19.0

Leads to pypicloud issues with the fallback cache:

```
[pid: 12325|app: 0|req: 269/2968] 172.17.0.3 () {38 vars in 857 bytes} [Wed May 24 18:53:49 2017] GET /simple/scipy/ => generated 45864 bytes in 118 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
INFO 2017-05-24 18:53:49,621 [pypicloud.views.api] Caching scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl from https://pypi.python.org/simple
Traceback (most recent call last):
  File "/env/local/lib/python2.7/site-packages/pyramid/router.py", line 233, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/env/local/lib/python2.7/site-packages/pyramid/router.py", line 208, in invoke_subrequest
    response = handle_request(request)
  File "/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 120, in tm_tween
    reraise(*exc_info)
  File "/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 109, in tm_tween
    manager.commit()
  File "/env/local/lib/python2.7/site-packages/transaction/_manager.py", line 131, in commit
    return self.get().commit()
  File "/env/local/lib/python2.7/site-packages/transaction/_transaction.py", line 310, in commit
    reraise(t, v, tb)
  File "/env/local/lib/python2.7/site-packages/transaction/_transaction.py", line 301, in commit
    self._commitResources()
  File "/env/local/lib/python2.7/site-packages/transaction/_transaction.py", line 446, in _commitResources
    reraise(t, v, tb)
  File "/env/local/lib/python2.7/site-packages/transaction/_transaction.py", line 418, in _commitResources
    rm.tpc_begin(self)
  File "/env/local/lib/python2.7/site-packages/zope/sqlalchemy/datamanager.py", line 96, in tpc_begin
    self.session.flush()
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2139, in flush
    self._flush(objects)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2259, in _flush
    transaction.rollback(_capture_exception=True)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2223, in _flush
[pid: 12325|app: 0|req: 270/2969] 172.17.0.3 () {36 vars in 1065 bytes} [Wed May 24 18:53:49 2017] GET /api/package/scipy/scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl => generated 0 bytes in 1390 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
    flush_context.execute()
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements
    execute(statement, multiparams)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
DataError: (psycopg2.DataError) value too long for type character varying(50)
 [SQL: 'INSERT INTO packages (filename, name, version, last_modified, summary, data) VALUES (%(filename)s, %(name)s, %(version)s, %(last_modified)s, %(summary)s, %(data)s)'] [parameters: {'name': u'scipy', 'filename': u'scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl', 'version': u'0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64', 'last_modified': datetime.datetime(2017, 5, 24, 18, 53, 50, 394873), 'summary': None, 'data': '{"path": "266b/scipy/scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl"}'}]
INFO 2017-05-24 18:53:51,288 [pypicloud.views.api] Caching scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl from https://pypi.python.org/simple
Traceback (most recent call last):
  File "/env/local/lib/python2.7/site-packages/pyramid/router.py", line 233, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/env/local/lib/python2.7/site-packages/pyramid/router.py", line 208, in invoke_subrequest
    response = handle_request(request)
  File "/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 120, in tm_tween
    reraise(*exc_info)
  File "/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 109, in tm_tween
    manager.commit()
  File "/env/local/lib/python2.7/site-packages/transaction/_manager.py", line 131, in commit
    return self.get().commit()
  File "/env/local/lib/python2.7/site-packages/transaction/_transaction.py", line 310, in commit
    reraise(t, v, tb)
  File "/env/local/lib/python2.7/site-packages/transaction/_transaction.py", line 301, in commit
    self._commitResources()
  File "/env/local/lib/python2.7/site-packages/transaction/_transaction.py", line 446, in _commitResources
    reraise(t, v, tb)
  File "/env/local/lib/python2.7/site-packages/transaction/_transaction.py", line 418, in _commitResources
    rm.tpc_begin(self)
  File "/env/local/lib/python2.7/site-packages/zope/sqlalchemy/datamanager.py", line 96, in tpc_begin
    self.session.flush()
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2139, in flush
    self._flush(objects)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2259, in _flush
    transaction.rollback(_capture_exception=True)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2223, in _flush
    flush_context.execute()
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements
    execute(statement, multiparams)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
DataError: (psycopg2.DataError) value too long for type character varying(50)
 [SQL: 'INSERT INTO packages (filename, name, version, last_modified, summary, data) VALUES (%(filename)s, %(name)s, %(version)s, %(last_modified)s, %(summary)s, %(data)s)'] [parameters: {'name': u'scipy', 'filename': u'scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl', 'version': u'0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64', 'last_modified': datetime.datetime(2017, 5, 24, 18, 53, 53, 211647), 'summary': None, 'data': '{"path": "266b/scipy/scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl"}'}]
[pid: 12325|app: 0|req: 271/2970] 172.17.0.3 () {36 vars in 1065 bytes} [Wed May 24 18:53:51 2017] GET /api/package/scipy/scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl => generated 0 bytes in 2340 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

Obviously one solution could be to raise the size of the version string, but it's not clear how big it should go.

**Comment by stevearc** [comment]
Fixed by #128
