### ISSUE TITLE
Question: always return SIZELIMIT_EXCEEDED: {'desc': 'Size limit exceeded'} 

### ISSUE THREAD

**Issue by FrankJian** [stevearc/pypicloud#132]
we have much data in the ldap server, so even i set auth.ldap.all_user_search to small scope, also will return much item which may cause the SIZELIMIT_EXCEEDED, is it possible to get the login account name in the uwsgi configuration? so we can set like below " auth.ldap.all_user_search=(uid=%user)"  to return only one item?

**Comment by stevearc** [comment]
I unfortunately do not know much about LDAP personally. I could give this a shot, but I'll need to write a bunch of tests first to make sure it all still works when I'm done.

**Comment by FrankJian** [comment]
hi stevearc, thanks for your looking :) 
for normally ldap server setting, there are 
"nssizelimit: 1000" and 
"nslookthroughlimit: 2000", 
that means the function 
results = LDAP._server.search_s(
            LDAP._base_dn,
            ldap.SCOPE_SUBTREE,
            LDAP._all_user_search,
        )
will may only return the max item(1000) of the result. , so i mean if we can limit the result by filter(just reduce the scope of the parameter "LDAP._all_user_search", so i think login name is the better key :) )

btw, i also not very familiar with the ldap setting, just google it

**Comment by FrankJian** [comment]
hi stevearc,
i see you committed some code to the branch 1.0 with some refactor of ldap , and i tried this branch, and seems everything are fine(just test login and logout ). i can specific the auth.ldap.user_search_filter=uid={username}, and it works .

do you have any plan to release this version?

btw, is it possible to change the type of auth.ldap.admin_value from string to list? as we may need specific someone with admin permission.

thanks.

**Comment by stevearc** [comment]
Yes I was planning to release that branch as 1.0.0rc2 as soon as I finish a few more tasks.

I'm not sure I understand what you want with the `admin_value`. I wrote some docs for `admin_field` and `admin_value`: http://pypicloud.readthedocs.io/en/1.0/topics/access_control.html#auth-ldap-admin-field

I think that you would be able to do what you want by adding an attribute to any user that you want to be an admin. If that doesn't work for you, I could add the ability to specify a list of DNs in the config file that would be admins.

**Comment by FrankJian** [comment]
hello stevearc,
thanks fro your updating

1. seems some configuration such as S3 is different between tag 0.5.4 and branch 1.0.
for example in 0.5.4, it use storage.access_key and storage.secret_key, but in branch 1.0, we use storage.aws_access_key_id and more configurations.  etc...
and the GUI seems also have some different.
i just means if it is possible to add the change based on the latest master branch ?

and i  use the 0.5.4 before, now i switch branch 1.0 for testing, the configuration(uwsgi configuration file) are the same but some storage and ldap configuration, i get the error below(use redis for cache, and works fine in 0.5.4):

[pid: 30|app: 0|req: 6/16] 10.140.178.40 () {40 vars in 990 bytes} [Mon Sep 11 02:08:32 2017] GET /static/1.0.0rc1/partial/upload.html => generated 0 bytes in 1 msecs (HTTP/1.1 304) 4 headers in 427 bytes (0 switches on core 0)
[pid: 21|app: 0|req: 1/17] 10.140.178.40 () {38 vars in 914 bytes} [Mon Sep 11 02:08:32 2017] GET /api/package/?verbose=true => generated 0 bytes in 11 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 755, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid_duh/view.py", line 181, in slash_redirect
    return fxn(*args)
  File "/usr/lib/python2.7/site-packages/pyramid_duh/params.py", line 306, in param_twiddler
    return fxn(**scope)
  File "/usr/lib/python2.7/site-packages/pypicloud/views/api.py", line 32, in all_packages
    packages = request.db.summary()
  File "/usr/lib/python2.7/site-packages/pypicloud/cache/redis_cache.py", line 96, in summary
    if summary['summary'] == '':
KeyError: u'summary'

2.
for admin_value, i just means if we can use the configuration sucn as below:
auth.ldap.admin_field = uid
auth.ldap.admin_value = 
      Bob
      Tom
      Tim

**Comment by stevearc** [comment]
I've pushed another update to the 1.0 branch. It should fix the redis crash and also allows a list of values for `auth.ldap.admin_value`. I still have a couple more things I want to do before releasing 1.0.0rc2, but I expect to get it out by Tuesday evening.

Unfortunately the LDAP changes required almost a complete rewrite, and a lot of settings changes. It was way too much to include in a patch release, which is why I'm putting it in the next major version update with all the other big changes.

**Comment by FrankJian** [comment]
yes. fine now.
thanks

**Comment by stevearc** [comment]
Released [1.0.0rc2](https://pypi.python.org/pypi/pypicloud/1.0.0rc2)

**Comment by FrankJian** [comment]
great.
thanks.
