### ISSUE TITLE
Pip search not working

### ISSUE THREAD

**Issue by koleror** [stevearc/pypicloud#148]
Hi,
It looks like pypicloud does not support the pip search command, which is very unfortunate as it also breaks the pip-compile command. 
Here is my traceback:
```
HTTP error 400 while getting http://<username>:<password>@<pypiserver>/simple/
Exception:
Traceback (most recent call last):
  File "/Users/koleror/venvs/core/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/koleror/venvs/core/lib/python2.7/site-packages/pip/commands/search.py", line 45, in run
    pypi_hits = self.search(query, options)
  File "/Users/koleror/venvs/core/lib/python2.7/site-packages/pip/commands/search.py", line 62, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/Users/koleror/venvs/core/lib/python2.7/site-packages/pip/download.py", line 77his 7, in request
    response.raise_for_status()
  File "/Users/koleror/venvs/core/lib/python2.7/site-packages/pip/_vendor/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request for url: http:/<pypiserver>/simple/
```

When I have a look at the query and response, here is what I get:
Request url : ```http://<username>:<password>@<pypiserver>/simple/```
Request body:
```
"<?xml version='1.0'?>\n<methodCall>\n<methodName>search</methodName>\n<params>\n<param>\n<value><struct>\n<member>\n<name>name</name>\n<value><array><data>\n<value><string>MY_PRIVATE_PACKAGE</string></value>\n</data></array></value>\n</member>\n<member>\n<name>summary</name>\n<value><array><data>\n<value><string>MY_PRIVATE_PACKAGE</string></value>\n</data></array></value>\n</member>\n</struct></value>\n</param>\n<param>\n<value><string>or</string></value>\n</param>\n</params>\n</methodCall>\n"
```

Response : ```400```
Response body :
```
"<html>\n <head>\n  <title>400 Bad Request</title>\n </head>\n <body>\n  <h1>400 Bad Request</h1>\n  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>\nMissing argument 'content'\n\n\n </body>\n</html>"
```
It does not work, whatever if I'm searching for private or public packages.
Is it an issue on my side or a missing/broken feature?

Thanks!

**Comment by stevearc** [comment]
Pip search should be working, but with a slightly different URL. Instead of `http://<username>:<password>@<pypiserver>/simple/`, try `http://<username>:<password>@<pypiserver>/pypi/`. I believe that using the `/pypi` path is the standard as that is given as the default in the [pip search docs](https://pip.pypa.io/en/stable/reference/pip_search/#options)

**Comment by koleror** [comment]
Indead it works, thank you!
