### ISSUE TITLE
Getting lots of 500 errors when handling exceptions

### ISSUE THREAD

**Issue by tomelliff** [stevearc/pypicloud#160]
Running 1.0.3 in a Docker container (with S3 storage and Postgres for auth and caching) I regularly have UI elements fail to load and logs show this repeatedly:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 744, in invoke_exception_view
    request_iface=request_iface.combined,
  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pypicloud/views/__init__.py", line 50, in format_exception
    LOG.exception(context.message)
AttributeError: 'AttributeError' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 748, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/local/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 744, in invoke_exception_view
    request_iface=request_iface.combined,
  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pypicloud/views/__init__.py", line 50, in format_exception
    LOG.exception(context.message)
AttributeError: 'OperationalError' object has no attribute 'message'
[pid: 40|app: 0|req: 1/17] 172.17.0.1 () {38 vars in 930 bytes} [Thu Mar 29 09:52:43 2018] GET /api/package/?verbose=true => generated 0 bytes in 93 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

Interestingly if there's regular access happening this seems to happen less/go away so at a complete guess I'd say that database connections are being dropped and then that bubbles up as an exception only for th exception handler to completely fall over.

I can provide the Dockerfile and config.ini I'm using if that helps at all but not sure what's happening here at first glance without digging too much into the project.

**Comment by stevearc** [comment]
Okay, I think I can reproduce the problem. The logging is a little broken in Python 3 so the messages aren't great, but in Python 2 I can see that there appear to be some issues with attempting to create a transaction when one is already open. Will try to get to a fix this weekend.

**Comment by tomelliff** [comment]
Thanks, going to test 1.0.4 now to see if that fixes things.

Out of curiosity any reason you're trying to use `e.message` instead of `str(e)` when exception handling? Would make Python3 not barf horribly when handling the exceptions and should work fine in Python2 as well.
