### ISSUE TITLE
S3 redirection failing SSL Cert validation on `pip install` from pypicloud behind an NGINX reverse proxy

### ISSUE THREAD

**Issue by AGloberman** [stevearc/pypicloud#161]
We've recently added an nginx container to do mutual auth in front of our pypicloud installation, but are running into a new issue with the S3 connectivity on the backend (SSL: CERTIFICATE_VERIFY_FAILED) when trying to pip install from this index.  I am able to add and remove packages via the web client and can `twine upload` packages to it from bash.  It's just the pull from bash that fails.  

We're running nginx 1.11 and pypicloud 1.0.2.

Here's our nginx config's relevant section:
`
server {
        listen                  443;
        ssl                     on;
        server_name             example.com;
        ssl_certificate         /path/to/cert.pem;
        ssl_certificate_key     /path/to/keycert.pem;
        ssl_client_certificate  /path/to/ca.chain.cert.pem;
        ssl_verify_client       on;
        ssl_verify_depth        4;

        location / {
            proxy_pass       http://127.0.0.1:8080;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Url-Scheme $scheme;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect   off;
        }
    }`

Here's our pypicloud config file:
`app:main]
use = egg:pypicloud

pyramid.reload_templates = false
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en

pypi.storage = s3
storage.bucket = eadp-pypi-cloud-dev
storage.region_name = us-east-1
storage.redirect_urls = true

pypi.default_read = everyone
pypi.default_write = everyone

db.url = sqlite:////var/lib/pypicloud/db.sqlite

session.encrypt_key = replaceme
session.validate_key = replaceme
session.secure = false

[uwsgi]
paste = config:%p
paste-logger = %p
master = true
processes = 20
reload-mercy = 15
worker-reload-mercy = 15
max-requests = 1000
virtualenv = /env
http = 0.0.0.0:8080

[loggers]
keys = root, boto

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_boto]
level = WARN
qualname = boto
handlers =

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)s %(asctime)s [%(name)s] %(message)s`

Here's the command we're running to test: 
`pip install -i https://example.com/pypi https://example.com/api/package/package.tar.gz --client-cert=/path/to/keycert.pem --cert=/path/to/ca.chain.cert.pem`

Which yields the following error: 
`Starting new HTTPS connection (5): eadp-pypi-cloud-dev.s3.amazonaws.com
  Incremented Retry for (url='/914c/<packageName>/<package>.tar.gz?Signature=<snip>&Expires=1522968734&AWSAccessKeyId=<snip>&x-amz-security-token=<snip>: Retry(total=0, connect=None, read=None, redirect=None, status=None)
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /914c/<packageName>/<package>.tar.gz?Signature=<snip>&Expires=1522968734&AWSAccessKeyId=<snip>&x-amz-security-token=<snip>
  Starting new HTTPS connection (6): eadp-pypi-cloud-dev.s3.amazonaws.com
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='eadp-pypi-cloud-dev.s3.amazonaws.com', port=443): Max retries exceeded with url: /914c/tenant-assets/tenant-assets-1.2.5.macosx-10.13-intel.tar.gz?Signature=<snip>&Expires=1522968734&AWSAccessKeyId=<snip>&x-amz-security-token=<snip> (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))`

**Comment by AGloberman** [comment]
Found this to be some good old-fashioned user error.  We needed to specify `trusted-host`, which got us past this issue.
