### ISSUE TITLE
No such table packages in docker container

### ISSUE THREAD

**Issue by kalgm** [stevearc/pypicloud#165]
I'm getting the following error when running the docker container with the in memory sqllite:// config.

```
ERROR 2018-04-13 23:06:08,118 [pypicloud.views] (sqlite3.OperationalError) no such table: packages [SQL: 'SELECT packages.filename AS packages_filename, packages.name AS packages_name, packages.version AS packages_version, packages.last_modified AS packages_last_modified, packages.summary AS packages_summary, packages.data AS packages_data \nFROM packages \nWHERE packages.name = ?'] [parameters: ('appdirs',)] (Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: packages

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid_duh/view.py", line 181, in slash_redirect
    return fxn(*args)
  File "/usr/local/lib/python3.5/dist-packages/pypicloud/views/simple.py", line 85, in package_versions
    return _simple_redirect(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pypicloud/views/simple.py", line 165, in _simple_redirect
    packages = request.db.all(normalized_name)
  File "/usr/local/lib/python3.5/dist-packages/pypicloud/cache/sql.py", line 160, in all
    pkgs = self.db.query(SQLPackage).filter_by(name=name).all()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2737, in all
    return list(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2889, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2912, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: packages [SQL: 'SELECT packages.filename AS packages_filename, packages.name AS packages_name, packages.version AS packages_version, packages.last_modified AS packages_last_modified, packages.summary AS packages_summary, packages.data AS packages_data \nFROM packages \nWHERE packages.name = ?'] [parameters: ('appdirs',)] (Background on this error at: http://sqlalche.me/e/e3q8)
[pid: 34|app: 0|req: 1/1] 172.17.0.1 () {34 vars in 701 bytes} [Fri Apr 13 23:06:08 2018] GET /simple/appdirs/ => generated 569 bytes in 32 msecs (HTTP/1.1 520) 2 headers in 91 bytes (1 switches on core 0)
```

My config is as follows:

```
[app:main]
use = egg:pypicloud

pyramid.reload_templates = False
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en

pypi.default_read = everyone
pypi.default_write = everyone

pypi.storage = s3
pypi.fallback = cache
#pypi.always_show_upstream = true
storage.aws_access_key_id = ************
storage.aws_secret_access_key = ***********************
storage.bucket = package-repository
storage.region_name = us-west-2
storage.prefix = pypi/

db.url = sqlite://
```

Any idea what is going on here? Thanks!

**Comment by stevearc** [comment]
I am not surprised that an in-memory sqlite doesn't work. I should probably mention this in the docs, but we are creating a connection to the DB, then uWSGI will fork into several processes, then we dispose of existing connections because there were some [corruption issues post-fork](https://github.com/stevearc/pypicloud/issues/160). I don't know if sqlite would even be able to support multiple processes connecting to a single in-memory database.

Is there a particular reason why you need it to be in-memory instead of a file in the docker container?

**Comment by ramseydsilva** [comment]
+1

**Comment by stevearc** [comment]
I wouldn't expect that to change anything. Unless there's a good reason not to, I'd recommend connecting sqlite to a file instead of using an in-memory db
```
db.url = sqlite:////var/lib/pypicloud/db.sqlite
```
