### ISSUE TITLE
Admin Download ACL button throws type error in Python3

### ISSUE THREAD

**Issue by tomelliff** [stevearc/pypicloud#166]
The UI gives me:
```json
{"error": "unknown", "message": "memoryview: a bytes-like object is required, not 'str'"}
```
When I click on the Download ACL button in the admin screen when running PyPICloud under Python3.

Stack trace:
```
ERROR 2018-04-16 16:51:13,138 [pypicloud.views] memoryview: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/usr/local/lib/python3.6/site-packages/pypicloud/views/admin.py", line 186, in download_access_control
    json.dump(data, zipfile, separators=(',', ':'))
  File "/usr/local/lib/python3.6/json/__init__.py", line 180, in dump
    fp.write(chunk)
  File "/usr/local/lib/python3.6/gzip.py", line 260, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'
[pid: 30|app: 0|req: 10/29] 172.17.0.1 () {42 vars in 1047 bytes} [Mon Apr 16 16:51:13 2018] GET /admin/acl.json.gz => generated 89 bytes in 31 msecs (HTTP/1.1 500) 3 headers in 413 bytes (1 switches on core 0)
```

Can be reproduced when running in Docker:
```
docker run -p8080:8080 --rm stevearc/pypicloud:1.0.4-py3-alpine
```

**Comment by stevearc** [comment]
Oof, confirmed. I'll try to find a way around the encoding error when writing to gzip

**Comment by koleror** [comment]
I found a way to fix this: 
```@view_config(name='acl.json.gz', request_method='GET')
    def download_access_control(self):
        """ Download the ACL data as a gzipped-json file """
        data = self.request.access.dump()
        compressed = six.BytesIO()
        data = bytes(json.dumps(data, separators=(',', ':')), 'utf-8')
        compressed.write(gzip.compress(data))
        compressed.seek(0)

        disp = CONTENT_DISPOSITION.tuples(filename='acl.json.gz')
        self.request.response.headers.update(disp)
        self.request.response.app_iter = FileIter(compressed)
        return self.request.response```

The only problem is the data will be in memory, but I'm not sure that's really a problem, as it will never get really big, can it?

**Comment by stevearc** [comment]
Oh, I've already put in a commit that does basically the same thing, I just haven't pushed it yet. I'll do that now
