### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int

### ISSUE THREAD

**Issue by grozail** [stevearc/pypicloud#198]
I have installed pypicloud using [this guide](https://pypicloud.readthedocs.io/en/latest/topics/getting_started.html).
I tried development and publishing using `ppc-make-config -t server.ini` and `pserve server.ini`. It worked.
Then I tried `ppc-make-config -p prod.ini` and `pserve prod.ini` and got this:

> Traceback (most recent call last):
  File "/home/admuser/rozumpypi/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/home/admuser/rozumpypi/lib/python3.6/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/home/admuser/rozumpypi/lib/python3.6/site-packages/pyramid/scripts/pserve.py", line 187, in run
    loader.setup_logging(config_vars)
  File "/home/admuser/rozumpypi/lib/python3.6/site-packages/plaster_pastedeploy/__init__.py", line 219, in setup_logging
    fileConfig(self.uri.path, defaults, disable_existing_loggers=False)
  File "/usr/lib/python3.6/logging/config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python3.6/logging/config.py", line 148, in _install_handlers
    h = klass(*args)
  File "/usr/lib/python3.6/logging/handlers.py", line 148, in __init__
    if maxBytes > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

Any ideas how to fix this behavior? Or should I report issue to pyramid?

**Comment by stevearc** [comment]
Try deleting the line `args = ('/var/log/pypicloud.log', 'mode=a', 'maxBytes=1000000', 'backupCount=5')` from the config. It looks like it's geting `maxBytes` as a string. You could also take the logging config from the "dev" version of the config, as that will just log to stdout. I'll investigate why this changed and what the better fix is when I have a minute

**Comment by grozail** [comment]
Thanks. I will try to find workaround using your suggestion. It still works in spite of this error.
