### ISSUE TITLE
boto3 forbidden from running s3 commands

### ISSUE THREAD

**Issue by fchorney** [stevearc/pypicloud#208]
So I currently am trying to get pypicloud running in an Amazon ECS instance using IAM authentication. I seem to be having this weird issue where the shell can make boto3 commands through python perfectly fine, but when the code in pypicloud tries to do the exact same thing it seems to be failing.

Example. I run the first line in the shell and it returns with a `404 Not Found`, which is correct because that bucket does not exist:
`$ python3 -c 'import boto3; s3conn = boto3.resource('\''s3'\''); head = s3conn.meta.client.head_bucket(Bucket='\''gotem'\'')'`
```python
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 661, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadBucket operation: Not Found
``` 

but then when pypicloud runs (prod set up using uwsgi) on this line https://github.com/stevearc/pypicloud/blob/master/pypicloud/storage/s3.py#L101 its giving me a `403 Forbidden` for some reason and I can't figure out any way to get it to work.
```python
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
return loadobj(APP, uri, name=name, **kw)
File "/usr/local/lib/python3.5/dist-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
return context.create()
File "/usr/local/lib/python3.5/dist-packages/paste/deploy/loadwsgi.py", line 715, in create
return self.object_type.invoke(self)
File "/usr/local/lib/python3.5/dist-packages/paste/deploy/loadwsgi.py", line 152, in invoke
return fix_call(context.object, context.global_conf, **context.local_conf)
File "/usr/local/lib/python3.5/dist-packages/paste/deploy/util.py", line 55, in fix_call
val = callable(*args, **kw)
File "/usr/local/lib/python3.5/dist-packages/pypicloud/__init__.py", line 182, in main
config.include("pypicloud")
File "/usr/local/lib/python3.5/dist-packages/pyramid/config/__init__.py", line 676, in include
c(configurator)
File "/usr/local/lib/python3.5/dist-packages/pypicloud/__init__.py", line 84, in includeme
config.include("pypicloud.cache")
File "/usr/local/lib/python3.5/dist-packages/pyramid/config/__init__.py", line 676, in include
c(configurator)
File "/usr/local/lib/python3.5/dist-packages/pypicloud/cache/__init__.py", line 27, in includeme
kwargs = cache_impl.configure(settings)
File "/usr/local/lib/python3.5/dist-packages/pypicloud/cache/dynamo.py", line 74, in configure
kwargs = super(DynamoCache, cls).configure(settings)
File "/usr/local/lib/python3.5/dist-packages/pypicloud/cache/base.py", line 42, in configure
"storage": get_storage_impl(settings),
File "/usr/local/lib/python3.5/dist-packages/pypicloud/storage/__init__.py", line 39, in get_storage_impl
kwargs = storage_impl.configure(settings)
File "/usr/local/lib/python3.5/dist-packages/pypicloud/storage/object_store.py", line 94, in configure
kwargs["bucket"] = cls.get_bucket(bucket_name, settings)
File "/usr/local/lib/python3.5/dist-packages/pypicloud/storage/s3.py", line 155, in get_bucket
head = s3conn.meta.client.head_bucket(Bucket=bucket_name)
File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 661, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden
```

Do you have any idea what the problem may be? Ive been trying to tackle this for a while and can't seem to figure it out.

Seems to be that the difference between the shell command and the pypicloud command is that in the later command there are many more layers before boto3 makes its call (paste, pyramid, uwsgi, pypicloud, etc) so I'm wondering if one of those layers is somehow messing up how boto3 is trying to contact aws.

**Comment by stevearc** [comment]
The first thing that looks weird to me is the stack. It's claiming the error is coming from line `s3.py:155, in get_bucket`. But that code isn't on line 155, it's on line 101. A quick skim through the history didn't show me any time when that code was on that line. What version of pypicloud are you running?

Second thought is that the calls aren't *exactly* the same. Pypicloud is creating its own boto config and passing that into the `boto3.resource` along with a bunch of other configuration options drawn from the config. Most of these should be None, but it's probably worth printing them all out and then putting exactly those values into the script that you're running to test the behavior.
https://github.com/stevearc/pypicloud/blob/master/pypicloud/storage/s3.py#L82-L97

**Comment by fchorney** [comment]
Yeah sorry I forgot to mention. I forked pypicloud and added a bunch of
print statements into it which is why the line numbers don’t match up. From
what I can tell inside pypicloud it looks like it has the same credentials
as in the shell but for whatever reason it doesn’t work the same. Is there
some other output I could get to help us debug this issue?

**Comment by fchorney** [comment]
I’ve also tested within pypicloud the exact same boto statements as my shell test without all those extra configs that pypicloud adds in and it still comes out as forbidden. You can see some of the tests I’ve thrown in here https://github.com/fchorney/pypicloud/blob/fc/tests/pypicloud/storage/s3.py

**Comment by stevearc** [comment]
You could bump up the log level of botocore and see what it's doing under the hood. Try changing it to `DEBUG`
https://github.com/stevearc/pypicloud/blob/feae61f02d3abd734d771f4a74159b460e98063a/pypicloud/templates/config.ini.jinja2#L125-L128

**Comment by fchorney** [comment]
Good call. I will try that thanks!

**Comment by fchorney** [comment]
so, it looks like this was an error on my part. It looks like s3 bucket names need to be globally unique, and the name that I chose was apparently taken by another account. Unfortunately the error only shows up as "forbidden" which wasn't necessarily helpful. I will close this, as this is not an issue with pypicloud. Thanks for the help! :)

**Comment by WeiguangYoung** [comment]
I meet this problem becase I set storage.aws_access_key_id = "XXX" instead of  storage.aws_access_key_id = XXX. I think it is unreasonable.
