### ISSUE TITLE
%(here)s no longer working in configuration file when upgrading from 0.5.3 -> 1.0.11

### ISSUE THREAD

**Issue by jochenhebbrecht** [stevearc/pypicloud#223]
Hi,

We recently switched from `0.5.3` to `1.0.11`, but we stumbled into a configuration issue when using `%(here)s`.

This is what we were using in `0.5.3`
```
db.url = sqlite:///%(here)s/db.sqlite
```
This is the error we were getting after upgrading to `1.0.11`:

```

10:30:39
Loading paste environment: config:/etc/pypicloud/config.ini

10:30:40
Traceback (most recent call last):

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2265, in _wrap_pool_connect

10:30:40
return fn()

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py", line 363, in connect

10:30:40
return _ConnectionFairy._checkout(self)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py", line 760, in _checkout

10:30:40
fairy = _ConnectionRecord.checkout(pool)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py", line 492, in checkout

10:30:40
rec = pool._do_get()

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/impl.py", line 238, in _do_get

10:30:40
return self._create_connection()

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py", line 308, in _create_connection

10:30:40
return _ConnectionRecord(self)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py", line 437, in __init__

10:30:40
self.__connect(first_connect_check=True)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py", line 639, in __connect

10:30:40
connection = pool._invoke_creator(self)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 114, in connect

10:30:40
return dialect.connect(*cargs, **cparams)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 453, in connect

10:30:40
return self.dbapi.connect(*cargs, **cparams)

10:30:40
sqlite3.OperationalError: unable to open database file

10:30:40
The above exception was the direct cause of the following exception:

10:30:40
Traceback (most recent call last):

10:30:40
File "/usr/local/lib/python3.5/dist-packages/paste/deploy/loadwsgi.py", line 253, in loadapp

10:30:40
return loadobj(APP, uri, name=name, **kw)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/paste/deploy/loadwsgi.py", line 278, in loadobj

10:30:40
return context.create()

10:30:40
File "/usr/local/lib/python3.5/dist-packages/paste/deploy/loadwsgi.py", line 715, in create

10:30:40
return self.object_type.invoke(self)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/paste/deploy/loadwsgi.py", line 152, in invoke

10:30:40
return fix_call(context.object, context.global_conf, **context.local_conf)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/paste/deploy/util.py", line 55, in fix_call

10:30:40
val = callable(*args, **kw)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/pypicloud/__init__.py", line 182, in main

10:30:40
config.include("pypicloud")

10:30:40
File "/usr/local/lib/python3.5/dist-packages/pyramid/config/__init__.py", line 676, in include

10:30:40
c(configurator)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/pypicloud/__init__.py", line 84, in includeme

10:30:40
config.include("pypicloud.cache")

10:30:40
File "/usr/local/lib/python3.5/dist-packages/pyramid/config/__init__.py", line 676, in include

10:30:40
c(configurator)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/pypicloud/cache/__init__.py", line 27, in includeme

10:30:40
kwargs = cache_impl.configure(settings)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/pypicloud/cache/sql.py", line 148, in configure

10:30:40
create_schema(engine)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/pypicloud/cache/sql.py", line 101, in create_schema

10:30:40
Base.metadata.create_all(bind=engine)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/schema.py", line 4287, in create_all

10:30:40
ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2035, in _run_visitor

10:30:40
with self._optional_conn_ctx_manager(connection) as conn:

10:30:40
File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__

10:30:40
return next(self.gen)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2027, in _optional_conn_ctx_manager

10:30:40
with self._contextual_connect() as conn:

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2229, in _contextual_connect

10:30:40
self._wrap_pool_connect(self.pool.connect, None),

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2269, in _wrap_pool_connect

10:30:40
e, dialect, self

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1536, in _handle_dbapi_exception_noconnection

10:30:40
util.raise_from_cause(sqlalchemy_exception, exc_info)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause

10:30:40
reraise(type(exception), exception, tb=exc_tb, cause=cause)

10:30:40
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise

10:30:40
raise value.with_traceback(tb)
```
This is our workaround in the config file:

```
db.url = sqlite:///var/lib/pypicloud/db.sqlite
```

Looking at the [changelog](https://pypicloud.readthedocs.io/en/latest/changes.html), I see it should have been fixed as of `1.0.6`:

```
Fix: Config file generation for use with docker container (using %(here)s was not working)
```
... but I think it's broken again in `1.0.11`. Would that be possible?

**Comment by stevearc** [comment]
The fix that you're referencing was 9dfa4e3a059266191b1a216f8ffaaa5477501ded. All it did was change the config file generation step to not produce paths with `%(here)s` when using the `-r` flag. I don't remember exactly what the error was when running in Docker, but I suspect that it's related to the fact that the config files are often mounted from the host filesystem so placing sqlite or other files in the same directory encounters permissions issues.

Are you running pypicloud inside docker? If so, the error is expected. If not, then we'll need to collect some more information to figure out what the `%(here)s` path is resolving to and why sqlalchemy is throwing while writing to it.

**Comment by jochenhebbrecht** [comment]
Hi @stevearc ,

Thanks for your very fast feedback!

Yes, we're running `pypicloud` inside Docker and the config file is on the host system (and using a volume mount, being mounted to `/etc/pypicloud/config.ini` inside the Docker itself).

If the error is expected, it means my "workaround" is also a proper fix? It's weird it used to work with the old version of `pypicloud-docker`, no?

Jochen

**Comment by stevearc** [comment]
Yes, you're doing the correct thing.

It is odd that it worked with the old version, but it's been so long and there have been so many changes that I'm not sure what could have made the difference.

**Comment by jochenhebbrecht** [comment]
Thanks @stevearc , closing this one as my question is answered!
