### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by lorddaedra** [stevearc/pypicloud#232]
I try to run pypicloud on Google Cloud Run (it's like cheap AWS Fargate, it provides serverless containers environment) with Google Cloud Storage. 

I can successfully run container but after I try to visit /admin/, I see "Service Unavailable" error. And in logs:
```
Traceback (most recent call last): 
File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp 
return loadobj(APP, uri, name=name, **kw) 
File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 278, in loadobj 
return context.create() 
File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 715, in create 
return self.object_type.invoke(self) 
File "/usr/local/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 152, in invoke 
return fix_call(context.object, context.global_conf, **context.local_conf) 
File "/usr/local/lib/python3.6/site-packages/paste/deploy/util.py", line 55, in fix_call 
val = callable(*args, **kw) 
File "/usr/local/lib/python3.6/site-packages/pypicloud/__init__.py", line 182, in main 
config.include("pypicloud") 
File "/usr/local/lib/python3.6/site-packages/pyramid/config/__init__.py", line 676, in include 
c(configurator) 
File "/usr/local/lib/python3.6/site-packages/pypicloud/__init__.py", line 84, in includeme 
config.include("pypicloud.cache") 
File "/usr/local/lib/python3.6/site-packages/pyramid/config/__init__.py", line 676, in include 
c(configurator) 
File "/usr/local/lib/python3.6/site-packages/pypicloud/cache/__init__.py", line 29, in includeme 
cache.reload_if_needed() 
File "/usr/local/lib/python3.6/site-packages/pypicloud/cache/sql.py", line 137, in reload_if_needed 
super(SQLCache, self).reload_if_needed() 
File "/usr/local/lib/python3.6/site-packages/pypicloud/cache/base.py", line 35, in reload_if_needed 
self.reload_from_storage(False) 
File "/usr/local/lib/python3.6/site-packages/pypicloud/cache/sql.py", line 272, in reload_from_storage 
return super(SQLCache, self).reload_from_storage(clear) 
File "/usr/local/lib/python3.6/site-packages/pypicloud/cache/base.py", line 74, in reload_from_storage 
for pkg in packages: 
File "/usr/local/lib/python3.6/site-packages/pypicloud/storage/gcs.py", line 141, in list 
pkg = self.package_from_object(blob, factory) 
File "/usr/local/lib/python3.6/site-packages/pypicloud/storage/gcs.py", line 132, in package_from_object 
name = blob.metadata.get("name") 
AttributeError: 'NoneType' object has no attribute 'get'
```

I tried to use default as possible settings

This is Dockerfile:
```
FROM python:3.6-alpine3.7
# https://github.com/stevearc/pypicloud-docker/blob/master/py3-alpine/Dockerfile

EXPOSE 8080
WORKDIR /app/

# Install packages required
ENV PYPICLOUD_VERSION 1.0.13
RUN set -ex \
    && apk upgrade --no-cache \
    && apk add --upgrade --no-cache --virtual build-deps \
         python3-dev mariadb-dev postgresql-dev build-base linux-headers openldap-dev \
    && apk add --upgrade --no-cache \
        libldap libpq mariadb-client-libs util-linux-dev libffi-dev \
    && python3 -m pip install --no-cache-dir --upgrade --upgrade-strategy=eager \
        setuptools \
        pip \
        wheel \
    && python3 -m pip install --no-cache-dir --upgrade --upgrade-strategy=eager \
        pypicloud[all_plugins]==$PYPICLOUD_VERSION requests uwsgi pastescript mysqlclient psycopg2-binary \
    && adduser -D -s /bin/sh -h /var/lib/pypicloud/ pypicloud \
    && apk del --no-cache build-deps \
    && mkdir -p /etc/pypicloud

# Add the command for easily creating config files
ADD config.ini /etc/pypicloud/config.ini
ADD make-config.sh /usr/local/bin/make-config

# Create a working directory for pypicloud
VOLUME /var/lib/pypicloud

# Run as pypicloud user
USER pypicloud

CMD ["uwsgi", "--die-on-term", "/etc/pypicloud/config.ini"]
```

Settings:
```
[app:main]
use = egg:pypicloud

pyramid.reload_templates = False
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en

pypi.default_read =
    authenticated
pypi.default_write =
    authenticated

pypi.storage = gcs
storage.bucket = packages-******************


db.url = sqlite://

auth.admins =
  myuser

user.myuser = ******************

# For beaker
session.encrypt_key = ******************
session.validate_key = ******************
session.secure = True
session.invalidate_corrupt = true

###
# wsgi server configuration
###

[uwsgi]
paste = config:%p
paste-logger = %p
master = true
processes = 20
reload-mercy = 15
worker-reload-mercy = 15
max-requests = 1000
enable-threads = true
http = 0.0.0.0:8080
uid = pypicloud
gid = pypicloud

###
# logging configuration
# http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
###

[loggers]
keys = root, botocore, pypicloud

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_pypicloud]
level = DEBUG
qualname = pypicloud
handlers =

[logger_botocore]
level = WARN
qualname = botocore
handlers =

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)s %(asctime)s [%(name)s] %(message)s

```

**Comment by stevearc** [comment]
Looking at the stacktrace, it appears that what's happening is upon startup the server tries to scan the storage backend (GCS) and find any existing packages with which to populate the cache. One of the blobs that it encounters has a `None` for the metadata, so it fails. I'll put in a fix that should help it ignore this file, but my recommendation is to use a fresh GCS for pypicloud so it doesn't collide with any existing files. You can also use an existing one and use an empty subdir by setting [storage.prefix](https://pypicloud.readthedocs.io/en/latest/topics/storage.html#id3)

**Comment by stevearc** [comment]
I believe this issue was resolved. Re-open if problems persist
