### ISSUE TITLE
Stack trace on some packages after upgrading to 1.1.0

### ISSUE THREAD

**Issue by dmarkey** [stevearc/pypicloud#250]
```Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/config/views.py", line 188, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/config/views.py", line 214, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 436, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid_duh/view.py", line 181, in slash_redirect
    return fxn(*args)
  File "/usr/local/lib/python3.5/dist-packages/pypicloud/views/simple.py", line 106, in package_versions
    return _package_versions(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pypicloud/views/simple.py", line 85, in _package_versions
    return _simple_redirect_always_show(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pypicloud/views/simple.py", line 233, in _simple_redirect_always_show
    pkgs = get_fallback_packages(request, context.name)
  File "/usr/local/lib/python3.5/dist-packages/pypicloud/views/simple.py", line 158, in get_fallback_packages
    "hash_sha256": release["digests"].get("sha256"),
AttributeError: 'tuple' object has no attribute 'get'
```

Using S3 and DynamoDB. Tried Rebuilding cache.

**Comment by dmarkey** [comment]
1.0.12 seems to work OK

**Comment by stevearc** [comment]
What package are you trying to pip install when you see the error?

**Comment by dmarkey** [comment]
```Collecting dnspython>=1.15.0 (from email_validator==1.0.3->-r requirements.txt (line 42))
[91mCould not install packages due to an EnvironmentError: HTTPSConnectionPool(host='pypicloud.xxx.xx', port=443): Max retries exceeded with url: /simple/dnspython/ (Caused by ResponseError('too many 500 error responses',))```

Seems to have been dnspython-1.15.0-py2.py3-none-any.whl
