### ISSUE TITLE
Upload to Azure Blob fails: The metadata specified is invalid

### ISSUE THREAD

**Issue by alanjcastonguay** [stevearc/pypicloud#271]
Backed by (what I think is) a fairly straightforward azure blob storage configuration, attempting to upload with `pypicloud==1.1.7` fails with `The metadata specified is invalid. It has characters that are not permitted.`.

The wheel uploaded doesn't seem to matter, but I reproduced following using `requests-2.25.1-py2.py3-none-any.whl` downloaded with `python3 -m pip download requests`.

<details>
  <summary>Logged Exception</summary>
    ```
ERROR 2021-01-05 19:48:08,520 [pypicloud.views] The metadata specified is invalid. It has characters that are not permitted.
RequestId:adc1b9d4-501e-002d-549b-e355a3000000
Time:2021-01-05T19:48:08.5013357Z
ErrorCode:InvalidMetadata
Error:None
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/storage/blob/_upload_helpers.py", line 106, in upload_block_blob
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 222, in upload
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'The metadata specified is invalid. It has characters that are not permitted.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
... snip
  File "/usr/local/lib/python3.5/dist-packages/pypicloud/views/simple.py", line 40, in upload
    requires_python=requires_python or None,
  File "/usr/local/lib/python3.5/dist-packages/pypicloud/cache/base.py", line 149, in upload
    self.storage.upload(new_pkg, data)
  File "/usr/local/lib/python3.5/dist-packages/pypicloud/storage/azure_blob.py", line 139, in upload
    blob_client.upload_blob(data=datastream, metadata=metadata)
  File "/usr/local/lib/python3.5/dist-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/azure/storage/blob/_blob_client.py", line 539, in upload_blob
    return upload_block_blob(**options)
  File "/usr/local/lib/python3.5/dist-packages/azure/storage/blob/_upload_helpers.py", line 158, in upload_block_blob
    process_storage_error(error)
  File "/usr/local/lib/python3.5/dist-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: The metadata specified is invalid. It has characters that are not permitted.
RequestId:adc1b9d4-501e-002d-549b-e355a3000000
Time:2021-01-05T19:48:08.5013357Z
ErrorCode:InvalidMetadata
Error:None
    ```
</details>

I added simple instrumentation print out `metadata` after `normalize_metadata()`; it's boring.

```python
{'hash-sha256': 'c210084e36a42ae6b9219e00e48287def368a26d03a048ddad7bfee44f75871e',
 'hash-md5': 'ec79209809129bf13cb002a0a573ef45',
 'name': 'requests',
 'version': '2.25.1'}
```

The culprit is the dash `-` character in the keys `hash-sha256` and `hash-md5`. https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#metadata-names says that "Metadata names must adhere to the naming rules for C# identifiers." Underscores work, which is the opposite of what `normalize_metadata()` does. This changed between 1.1.2 and 1.1.3.

Success logging with 1.1.2:
```
INFO 2021-01-05 15:53:08,686 [azure.core.pipeline.policies.http_logging_policy]     'x-ms-meta-hash_sha256': 'REDACTED'
INFO 2021-01-05 15:53:08,687 [azure.core.pipeline.policies.http_logging_policy]     'x-ms-meta-hash_md5': 'REDACTED'
INFO 2021-01-05 15:53:08,687 [azure.core.pipeline.policies.http_logging_policy]     'x-ms-meta-name': 'REDACTED'
INFO 2021-01-05 15:53:08,688 [azure.core.pipeline.policies.http_logging_policy]     'x-ms-meta-version': 'REDACTED'
```

Failure logging with 1.1.3:
```
INFO 2021-01-05 15:54:06,397 [azure.core.pipeline.policies.http_logging_policy]     'x-ms-meta-hash-sha256': 'REDACTED'
INFO 2021-01-05 15:54:06,397 [azure.core.pipeline.policies.http_logging_policy]     'x-ms-meta-hash-md5': 'REDACTED'
INFO 2021-01-05 15:54:06,398 [azure.core.pipeline.policies.http_logging_policy]     'x-ms-meta-name': 'REDACTED'
INFO 2021-01-05 15:54:06,398 [azure.core.pipeline.policies.http_logging_policy]     'x-ms-meta-version': 'REDACTED'
```

This was changed by @everpcpc in https://github.com/stevearc/pypicloud/commit/b355773fd145ff401687db7890ae2a55e79ca78e for S3, though I'm not aware of why.

**Comment by everpcpc** [comment]
related pr: https://github.com/stevearc/pypicloud/pull/255

It seems azure blob has a different consideration for https://github.com/stevearc/pypicloud/issues/254
