### ISSUE TITLE
alpine docker image fails to run

### ISSUE THREAD

**Issue by dvarrazzo** [stevearc/pypicloud#292]
Trying `stevearc/pypicloud:1.3.2-alpine` I get the traceback:

```
/app $ "uwsgi" "--die-on-term" "/etc/pypicloud/config.ini"
[uWSGI] getting INI configuration from /etc/pypicloud/config.ini
*** Starting uWSGI 2.0.20 (64bit) on [Sun Nov  7 03:30:24 2021] ***
compiled with version: 9.3.0 on 16 October 2021 17:21:04
os: Linux-5.10.0-7-cloud-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28)
nodename: pypicloud-68bd5c4d8c-lswb5
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:6543 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:38755 (port auto-assigned) fd 3
Python version: 3.8.10 (default, May  4 2021, 19:15:20)  [GCC 9.3.0]
Python main interpreter initialized at 0x55f84698ee40
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 15 seconds
mapped 1531320 bytes (1495 KB) for 20 cores
*** Operational MODE: preforking ***
Loading paste environment: config:/etc/pypicloud/config.ini
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyramid/path.py", line 387, in _zope_dottedname_style
    found = getattr(found, n)
AttributeError: module 'pypicloud' has no attribute 'cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/usr/local/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python3.8/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/pypicloud/__init__.py", line 208, in main
    config.include("pypicloud")
  File "/usr/local/lib/python3.8/site-packages/pyramid/config/__init__.py", line 666, in include
    c(configurator)
  File "/usr/local/lib/python3.8/site-packages/pypicloud/__init__.py", line 90, in includeme
    config.include("pypicloud.cache")
  File "/usr/local/lib/python3.8/site-packages/pyramid/config/__init__.py", line 632, in include
    c = self.maybe_dotted(callable)
  File "/usr/local/lib/python3.8/site-packages/pyramid/config/__init__.py", line 740, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/usr/local/lib/python3.8/site-packages/pyramid/path.py", line 327, in maybe_resolve
    return self._resolve(dotted, package)
  File "/usr/local/lib/python3.8/site-packages/pyramid/path.py", line 334, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/usr/local/lib/python3.8/site-packages/pyramid/path.py", line 389, in _zope_dottedname_style
    __import__(used)
  File "/usr/local/lib/python3.8/site-packages/pypicloud/cache/__init__.py", line 6, in <module>
    from .base import ICache
  File "/usr/local/lib/python3.8/site-packages/pypicloud/cache/base.py", line 12, in <module>
    from pypicloud.storage import get_storage_impl
  File "/usr/local/lib/python3.8/site-packages/pypicloud/storage/__init__.py", line 9, in <module>
    from .s3 import CloudFrontS3Storage, S3Storage
  File "/usr/local/lib/python3.8/site-packages/pypicloud/storage/s3.py", line 12, in <module>
    from cryptography.hazmat.primitives import hashes, serialization
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/__init__.py", line 15, in <module>
    from cryptography.hazmat.primitives.serialization.base import (
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 11, in <module>
    from cryptography.hazmat.primitives.asymmetric.types import (
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/types.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric import (
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 12, in <module>
    from cryptography.hazmat.primitives.asymmetric import (
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/utils.py", line 6, in <module>
    from cryptography.hazmat.bindings._rust import asn1
ImportError: Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/lib/python3.8/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
```
the non-alpine variant seems to run ok.

**Comment by stevearc** [comment]
Thanks for the report! Should be fixed in the 'latest-alpine' tag now

**Comment by feliperfmarques** [comment]
Thanks @stevearc. Could also you tag alpine-latest image with a specific version tag, please. This will ensure that I will always pull the same version. Having in mind that the specific version tag will not be overwritten, unlike what will probably happen with the latest and alpine-latest tag.

**Comment by stevearc** [comment]
Yep! Pushed to `1.3.2-1-alpine` as well

**Comment by feliperfmarques** [comment]
Thanks so much @stevearc
