### ISSUE TITLE
Exception while using ppc-create-s3-sync 

### ISSUE THREAD

**Issue by ppelletier** [stevearc/pypicloud#323]
Hi!

I'm trying to follow the instructions about 'Using S3 Notifications to sync caches' and I have an exception when running the script

```
ppc-create-s3-sync config.ini

Traceback (most recent call last):
  File "/opt/homebrew/bin/ppc-create-s3-sync", line 9, in <module>
    sys.exit(create_sync_scripts())
  File "/opt/homebrew/lib/python3.10/site-packages/pypicloud/lambda_scripts.py", line 291, in create_sync_scripts
    kwargs = S3Storage.configure(settings)
  File "/opt/homebrew/lib/python3.10/site-packages/pypicloud/storage/object_store.py", line 83, in configure
    kwargs.update(cls._subclass_specific_config(settings, kwargs))
  File "/opt/homebrew/lib/python3.10/site-packages/pypicloud/storage/s3.py", line 58, in _subclass_specific_config
    return {"sse": sse, "bucket": cls.get_bucket(bucket_name, settings)}
  File "/opt/homebrew/lib/python3.10/site-packages/pypicloud/storage/s3.py", line 66, in get_bucket
    config_settings = settings.get_as_dict(
AttributeError: 'ConfigDict' object has no attribute 'get_as_dict'
```

I tried to debug a bit and while settings is defined as EnvironSettings when I print the class I get <class 'plaster_pastedeploy.ConfigDict'>

```
def get_bucket(
        cls, bucket_name: str, settings: EnvironSettings
    ) -> "boto3.s3.Bucket":
        config_settings = settings.get_as_dict(
```

Any ideas why it doesn't work? And how I could make it work? :)
Thanks!

**Comment by stevearc** [comment]
Ah, this probably broke when I added the EnvironSettings helper. This flow has never been well tested because I suspect it's rarely used, so I'm not surprised to see some code rot. If that's the only issue, the fix might be pretty simple.
https://github.com/stevearc/pypicloud/blob/3016cc995b2a0f00f6fad0430a977894e789afe6/pypicloud/lambda_scripts.py#L196
Try changing this line to `settings = EnvironSettings(get_appsettings(args.config))` (and add `from pypicloud.util import EnvironSettings` at the top)
