### ISSUE TITLE
ConditionalCheckFailedException when rebuilding DynamoDB index from datastore

### ISSUE THREAD

**Issue by patricklucas** [stevearc/pypicloud#66]
I have a preexisting bucket with a large number of packages (~15000) and I'm trying out pypicloud 0.3.7 using the DynamoDB cache.

When I click 'Rebuild package list' from the admin console, it runs for 30–60 sec before failing with a ConditionalCheckFailedException[1] and stops. Each time it makes a little more progress, though.

Any tips on debugging this further?

[1]

```
content-type;host;user-agent;x-amz-date;x-amz-security-token;x-amz-target
a668c406474e5a233dc05445439efc3f6887a7381c4142e473f42d86b4f2e304
DEBUG 2016-01-22 10:57:57,385 [botocore.auth] StringToSign:
AWS4-HMAC-SHA256
20160122T185757Z
20160122/us-west-1/dynamodb/aws4_request
f8ecd4f3db43a4aaf8fafa947a684f4042d8b74292c93faf8725212f21f71e9c
DEBUG 2016-01-22 10:57:57,385 [botocore.auth] Signature:
a6900b98116d3f221b8821cbb2b4eeb1efcdd3d01823665d209de4854d437824
DEBUG 2016-01-22 10:57:57,386 [botocore.endpoint] Sending http request: <PreparedRequest [POST]>
DEBUG 2016-01-22 10:57:57,391 [botocore.vendored.requests.packages.urllib3.connectionpool] "POST / HTTP/1.1" 400 120
DEBUG 2016-01-22 10:57:57,392 [botocore.parsers] Response headers: {'x-amzn-requestid': 'O580VB8MLHT0IFGBF9M2OKS5NBVV4KQNSO5AEMVJF66Q9ASUAAJG', 'date': 'Fri, 22 Jan 2016 18:57:56 GMT', 'content-length': '120', 'content-type': 'application/x-amz-json-1.0', 'x-amz-crc32': '396270901'}
DEBUG 2016-01-22 10:57:57,392 [botocore.parsers] Response body:
{"__type":"com.amazonaws.dynamodb.v20120810#ConditionalCheckFailedException","message":"The conditional request failed"}
DEBUG 2016-01-22 10:57:57,392 [botocore.hooks] Event needs-retry.dynamodb.UpdateItem: calling handler <botocore.retryhandler.RetryHandler object at 0x7ffbd4a74f50>
DEBUG 2016-01-22 10:57:57,392 [botocore.retryhandler] No retry needed.
DEBUG 2016-01-22 10:57:57,393 [txn.140719567050496] abort
ERROR 2016-01-22 10:57:57,394 [waitress] Exception when serving /admin/rebuild
Traceback (most recent call last):
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/waitress/channel.py", line 336, in service
    task.service()
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/waitress/task.py", line 388, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid/router.py", line 223, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid/config/views.py", line 328, in attr_view
    return view(context, request)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid/config/views.py", line 304, in predicate_wrapper
    return view(context, request)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid/config/views.py", line 244, in _secured_view
    return view(context, request)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid/config/views.py", line 353, in rendered_view
    result = view(context, request)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pyramid/config/views.py", line 483, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pypicloud/views/admin.py", line 26, in rebuild_package_list
    self.request.db.reload_from_storage()
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pypicloud/cache/base.py", line 73, in reload_from_storage
    self.save(pkg)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/pypicloud/cache/dynamo.py", line 184, in save
    self.engine.sync(summary)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/flywheel/engine.py", line 618, in sync
    updates, returns=ALL_NEW, **keywords)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/dynamo3/connection.py", line 869, in update_item
    **keywords)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/dynamo3/connection.py", line 232, in call
    exc.re_raise()
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/dynamo3/exception.py", line 22, in re_raise
    six.reraise(type(self), self, self.exc_info[2])
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/dynamo3/connection.py", line 222, in call
    data = op(**kwargs)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/share/python/pypicloud/local/lib/python2.7/site-packages/botocore/client.py", line 407, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ConditionalCheckFailedException: ConditionalCheckFailedException: The conditional request failed
```

**Comment by patricklucas** [comment]
It appears that there is only one record in the PackageSummary table _per package_ instead of per version, so one theory would be that this is the result of an attempted update after an eventually-consistent read when updating the metadata for a package for which many versions exist in the datastore.

**Comment by patricklucas** [comment]
Hmm I tried changing

```python
        self.engine.sync(summary)
```

to

```python
        self.engine.sync(summary, consistent=True)
```

in [`cache/dynamo.py`](https://github.com/mathcamp/pypicloud/blob/876a722953f16382edff3b5a4dfc9675595deb2c/pypicloud/cache/dynamo.py#L184), but once again I saw that exception after 69 seconds or so.

**Comment by stevearc** [comment]
Hey Patrick, I'm out of town at the moment, but I'll look into this once I get back. It's not immediately obvious what could be causing it.

**Comment by pkoch** [comment]
Hey, guys! Picking up where @patricklucas left off.

It was, indeed, a stale reads problem. Adding `consistent=True` to `sync` ensures the read that's made after the write is consistent. However, we need the first read, not that one, to be consistent. See https://github.com/mathcamp/flywheel/blob/master/flywheel/engine.py#L515 The only time it uses `consistent` is on the very last statement.

I got around this by asking for consistency on the `get` on https://github.com/mathcamp/pypicloud/blob/master/pypicloud/cache/dynamo.py#L177.

Spelunking a bit lead to believe this is only used when we need to rebuild the cache or when uploading a new package version. I expect the perf impact of this change to be very tolerable for both those scenarios.

Moving to put a PR up.

**Comment by stevearc** [comment]
@patricklucas I took your suggestion from #67 and changed the `rebuild_from_storage` behavior to perform a more graceful merge, instead of blowing away and recreating the entire cache. I'm hoping that this will fix your issue; could you test it for me? The change is over on the [0.3 branch](https://github.com/mathcamp/pypicloud/commits/0.3)

@pkoch Thanks for digging into the code to get a fix! I'm hoping that the graceful reload change will fix the issue, but if not then I'll merge your PR as a workaround.
