### ISSUE TITLE
Create user error

### ISSUE THREAD

**Issue by luizgois-luizalabs** [stevearc/pypicloud#75]
Command: curl -X PUT -d 'password=test' http://localhost:3031/api/user/test

Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 223, in **call**
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid_tm/**init**.py", line 101, in tm_tween
    reraise(_exc_info)
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid_tm/**init**.py", line 83, in tm_tween
    response = handler(request)
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 602, in __call__
    return view(context, request)
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 328, in attr_view
    return view(context, request)
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 304, in predicate_wrapper
    return view(context, request)
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 353, in rendered_view
    result = view(context, request)
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pyramid_duh/params.py", line 306, in param_twiddler
    return fxn(_*scope)
  File "/home/ubuntu/virtualenvs/venv/local/lib/python2.7/site-packages/pypicloud/views/api.py", line 134, in register
    request.access.register(username, password)
AttributeError: 'ConfigAccessBackend' object has no attribute 'register'

**Comment by stevearc** [comment]
Hi! Can I ask which of the [access control backends](http://pypicloud.readthedocs.org/en/latest/topics/access_control.html) you are using? From the look of it I'd guess you're using a static one like the ini config file. In order to dynamically change the user records you'll need to use a dynamic backend like SQL.
